# Copyright (c) IBM Corporation.
# Copyright (c) Microsoft Corporation.
- name: CLIENT_ID
  value: ""
  description: Client ID for an Azure AD application registered in the Partner Center
- name: DATABASE_PASSWORD
  value: ""
  description: Password for database user db2inst1 (IBM DB2) and testuser (other database types)
- name: SECRET_VALUE
  value: ""
  description: Secret value of the Azure AD application registered in the Partner Center
- name: TENANT_ID
  value: ""
  description: Tenant ID of the Azure AD application registered in the Partner Center
- name: USER_NAME
  value: ""
  description: User name of GitHub account
- name: VM_ADMIN_ID
  value: ""
  description: User name for VM/Admin account
- name: VM_ADMIN_PASSWORD
  value: ""
  description: Password for VM/Admin account
## Optional parameters: if you want to use optional parameters, please uncomment the following lines
#- name: MSTEAMS_WEBHOOK
#  value: ""
#  description: [Optional] Web hook for Microsoft Teams channel
